apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-service
env:
  - name: LANGFUSE_PUBLIC_KEY
    value: "pk_XXX_XXX_XXXX_XXXXX"
  - name: LANGFUSE_SECRET_KEY
    value: "sk-XXX_XXX_XXXX_XXXXX"
  - name: LANGFUSE_HOST
    value: "http://langfuse.langfuse.svc.cluster.local:3000"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-service
  template:
    metadata:
      labels:
        app: rag-service
    spec:
      containers:
        - name: rag-service
          image: .amazonaws.com/rag-service:v13
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  type: LoadBalancer
  selector:
    app: rag-service
  ports:
    - port: 80
      targetPort: 8000